// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1ba_nuy1wI7LvlBxwMxw3GjwwCPWR0_E',
    appId: '1:131008852529:web:313729a706ad15741d5b10',
    messagingSenderId: '131008852529',
    projectId: 'opulenza-b5db7',
    authDomain: 'opulenza-b5db7.firebaseapp.com',
    storageBucket: 'opulenza-b5db7.firebasestorage.app',
    measurementId: 'G-2B3X18CP6C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADnr4vGEkKaeYvkigg0npyyIAT3UQGkZ8',
    appId: '1:131008852529:android:6140844c443f8c7e1d5b10',
    messagingSenderId: '131008852529',
    projectId: 'opulenza-b5db7',
    storageBucket: 'opulenza-b5db7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQjz6MWGGT_4L9975wbY3zSyjgiPyUK8g',
    appId: '1:131008852529:ios:2d68af8524a385f91d5b10',
    messagingSenderId: '131008852529',
    projectId: 'opulenza-b5db7',
    storageBucket: 'opulenza-b5db7.firebasestorage.app',
    iosBundleId: 'com.example.opulenza',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQjz6MWGGT_4L9975wbY3zSyjgiPyUK8g',
    appId: '1:131008852529:ios:2d68af8524a385f91d5b10',
    messagingSenderId: '131008852529',
    projectId: 'opulenza-b5db7',
    storageBucket: 'opulenza-b5db7.firebasestorage.app',
    iosBundleId: 'com.example.opulenza',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1ba_nuy1wI7LvlBxwMxw3GjwwCPWR0_E',
    appId: '1:131008852529:web:6d03709d5b68a62f1d5b10',
    messagingSenderId: '131008852529',
    projectId: 'opulenza-b5db7',
    authDomain: 'opulenza-b5db7.firebaseapp.com',
    storageBucket: 'opulenza-b5db7.firebasestorage.app',
    measurementId: 'G-E207ZJ6SP9',
  );
}
